-- ========================================================================
-- 有給休暇自動付与のスケジュールジョブを設定
-- pg_cron を使用して毎年4月1日 JST 0:00 (UTC 15:00) に Edge Function を呼び出す
-- ========================================================================

CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

-- ========================================================================
-- 本番環境セットアップ手順
-- ========================================================================
--
-- 1. Supabase Dashboard → Database → Extensions で pg_cron を有効化
--
-- 2. Dashboard → SQL Editor で以下の設定値を登録:
--    ALTER DATABASE postgres SET app.settings.supabase_url = 'https://<project-ref>.supabase.co';
--    ALTER DATABASE postgres SET app.settings.service_role_key = '<service-role-key>';
--
-- 3. Dashboard → SQL Editor で以下のcronジョブを登録:
--
--    -- 毎年4月1日 JST 0:00 (UTC 15:00) に有給自動付与
--    SELECT cron.schedule(
--      'auto-grant-leave',
--      '0 15 1 4 *',
--      $$
--      SELECT extensions.http_post(
--        url := current_setting('app.settings.supabase_url') || '/functions/v1/auto-grant-leave',
--        headers := jsonb_build_object(
--          'Content-Type', 'application/json',
--          'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key')
--        ),
--        body := '{}'::jsonb
--      )
--      $$
--    );
--
-- 4. ジョブ登録確認:
--    SELECT * FROM cron.job;
--
-- 5. 実行履歴確認:
--    SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 10;
--
-- ========================================================================
-- pg_cron はプロジェクトの設定により利用可能かどうかが異なるため、
-- 本マイグレーションでは拡張の有効化のみ行い、ジョブ登録は上記手順で行う
-- ========================================================================
